// ── Dicționarul englez ───────────────────────────────────────────────────────
//
// Cheia e TEXTUL ROMÂNESC, exact cum e scris în cod. Vezi `lib/i18n.tsx` pentru
// de ce așa.
//
// Un text care lipsește de aici NU strică nimic: se afișează în română. De asta
// există `scripts/i18n-scan.mjs`, care le găsește — altfel ar rămâne românești
// pentru totdeauna, fiindcă la testarea în română arată perfect.
//
// TERMENII DE TRADING vin din dicționarul site-ului (`apps/web/messages/en.json`),
// ca cineva care trece de pe site pe telefon să citească aceleași cuvinte:
// „Rată de câștig" → „Win rate", nu „Winning rate".

export const EN: Record<string, string> = {
  "Acasă": "Home",
  "Adaugă": "Add",
  "Adaugă primul cont": "Add your first account",
  "Adaugă tranzacție": "Add trade",
  "Alătură-te": "Join",
  "Am o confirmare de intrare (CHoCH / BOS / retest)": "I have an entry confirmation (CHoCH / BOS / retest)",
  "Analiză": "Analysis",
  "Analizează cu AI": "Analyze with AI",
  "București": "Bucharest",
  "Bună dimineața": "Good morning",
  "Bună seara": "Good evening",
  "Bună ziua": "Good afternoon",
  "Calculator lot": "Lot calculator",
  "Calendar economic": "Economic calendar",
  "Câștig brut": "Gross gain",
  "Contul meu": "My account",
  "Conturi de trading": "Trading accounts",
  "Conturi nelimitate": "Unlimited accounts",
  "Cumpărare": "Buy",
  "Drawdown maxim": "Max drawdown",
  "Editează": "Edit",
  "Există un punct de interes clar (Order Block / FVG / lichiditate)": "There's a clear point of interest (Order Block / FVG / liquidity)",
  "Fără reguli": "No rules",
  "Fără SL": "No SL",
  "Ieși": "Leave",
  "Ieșire": "Exit",
  "Ieșire prematură": "Early exit",
  "Intrare târzie": "Late entry",
  "În desfășurare": "In progress",
  "Înapoi": "Back",
  "Înapoi la autentificare": "Back to sign in",
  "Încearcă din nou": "Try again",
  "Închide": "Close",
  "Închise": "Closed",
  "Încrezător": "Confident",
  "Lecție": "Lesson",
  "Manager de risc": "Risk manager",
  "Marchează toate ca citite": "Mark all as read",
  "Notificări": "Notifications",
  "Nu există știri de impact major în următoarele 30 min": "There's no major-impact news in the next 30 min",
  "Nu tranzacționez din răzbunare, FOMO sau plictiseală": "I'm not trading out of revenge, FOMO or boredom",
  "Parolă": "Password",
  "Performanță": "Performance",
  "Perioadă": "Period",
  "Pierdere brută": "Gross loss",
  "Piețe": "Markets",
  "Preț": "Price",
  "Profit lunar": "Monthly profit",
  "Publică": "Public",
  "Realizări": "Achievements",
  "Risc de ruină": "Risk of ruin",
  "Risc depășit": "Risk exceeded",
  "Risc pe tranzacție": "Risk per trade",
  "Riscul per tranzacție respectă regula mea (≤ 1-2% din cont)": "Risk per trade respects my rule (≤ 1-2% of the account)",
  "Risk:Reward este minim 1:2": "Risk:Reward is at least 1:2",
  "Rulează din nou": "Run again",
  "Salvează modificările": "Save changes",
  "Salvează obiectivele": "Save goals",
  "Salvează regulile": "Save rules",
  "Salvează strategia": "Save the strategy",
  "Sâm": "Sat",
  "Setări": "Settings",
  "Stop Loss-ul este plasat logic (sub/peste structură), nu arbitrar": "The Stop Loss is placed logically (below/above structure), not arbitrarily",
  "Sunt calm și odihnit — starea mea mentală e bună": "I'm calm and rested — my mental state is good",
  "Sunt în sesiunea potrivită (Londra / New York / overlap)": "I'm in the right session (London / New York / overlap)",
  "Șterge": "Delete",
  "Șterge toate desenele": "Delete all drawings",
  "tranzacții": "trades",
  "Tranzacții": "Trades",
  "Trendul/structura HTF (H4/D1) susține direcția tranzacției": "The HTF trend/structure (H4/D1) supports the trade direction",
  "Vânzare": "Sell",
  "Verificare în doi pași": "Two-step verification",
  "Verifică emailul": "Check your email",
  "Vezi planurile": "See plans",
  "Win rate": "Win rate",
  "Zile de tranzacționare": "Trading days",
  "Zile minime": "Minimum days",
  "Zonă periculoasă": "Danger zone",
  "Notă": "Note",
  "Rată": "Rate",
  "Rămân": "Left",
  "eșuat": "failed",
  "Firmă": "Firm",
  "Mișcă": "Moves",
  "ȘTERG": "DELETE",
  "De la": "From",
  "ȚINTĂ": "TARGET",
  "De ce": "Why",
  "Știri": "News",
  "Piață": "Market",
  "Notițe": "Notes",
  "Lecții": "Lessons",
  "Citită": "Read",
  "rulări": "runs",
  "echipă": "team",
  "notată": "annotated",
  "Renunț": "Cancel",
  "vânzare": "sell",
  "Ai deja": "You already have",
  "Capcană": "Trap",
  "Pe luni": "By month",
  "Trecută": "Passed",
  "Postări": "Posts",
  "închisă": "closed",
  "Unealtă": "Tool",
  "O cifră": "A digit",
  "Temător": "Fearful",
  "VÂNZARE": "SELL",
  "Cotații": "Quotes",
  "Renunță": "Cancel",
  "Până la": "Until",
  "ȚINTĂ 2": "TARGET 2",
  "Închisă": "Closed",
  "opțional": "optional",
  "Deschisă": "Open",
  "deschisă": "open",
  "Întreabă": "Ask",
  "Nu chiar": "Not really",
  "CONTINUĂ": "CONTINUE",
  "Necitită": "Unread",
  "RR mediu": "Avg RR",
  "Pe setup": "By setup",
  "Rulează…": "Running…",
  "Secțiune": "Section",
  "Cont nou": "New account",
  "Pe trend": "By trend",
  "Execuția": "Execution",
  "De notat": "To log",
  "Conținut": "Content",
  "nesetată": "not set",
  "în lucru": "in progress",
  "Urmărite": "Watched",
  "Lista ta": "Your list",
  "Mai mult": "More",
  "Învățare": "Learning",
  "Stop loss": "Stop loss",
  "P&L total": "Total P&L",
  "cumpărare": "buy",
  "Terminată": "Completed",
  "La lecții": "To lessons",
  "Săptămâna": "Week",
  "Prop firm": "Prop firm",
  "Păstrează": "Keep",
  "Răzbunare": "Revenge",
  "fără notă": "no note",
  "CUMPĂRARE": "BUY",
  "Unde ești": "Where you stand",
  "Piața azi": "Market today",
  "Deblocată": "Unlocked",
  "Corelații": "Correlations",
  "Începător": "Beginner",
  "tranzacție": "trade",
  "Următoarea": "Next",
  "Mai târziu": "Later",
  "Comentează": "Comment",
  "comentează": "comment",
  "Altă firmă": "Other firm",
  "Se va crea": "Will create",
  "Cum e acum": "How it stands",
  "Închisă la": "Closed at",
  "Pe conturi": "By account",
  "Lot greșit": "Wrong lot size",
  "Tranzacție": "Trade",
  "gol = fără": "empty = none",
  "Noapte bună": "Good night",
  ", terminată": ", completed",
  "Reia quizul": "Retake the quiz",
  "Ești la zi.": "You're all caught up.",
  "Poate greși": "Can be wrong",
  "Take profit": "Take profit",
  "Order block": "Order block",
  "Despre tine": "About you",
  "Niciun cont": "No account",
  "Exportă CSV": "Export CSV",
  "Datele mele": "My data",
  "Profit brut": "Gross profit",
  "Sold curent": "Current balance",
  "Următoarele": "Up next",
  "Impact mare": "High impact",
  "Ce e TradeGX": "What TradeGX is",
  "Cel mai ales": "Most chosen",
  "Se gândește…": "Thinking…",
  "Toate citite": "All read",
  "Nicio alertă": "No alerts",
  "Rezultat net": "Net result",
  "Câștig mediu": "Average win",
  "Cea mai bună": "Best",
  "0 tranzacții": "0 trades",
  "Cum o cheamă": "What's it called",
  "Sold inițial": "Starting balance",
  "Reanalizează": "Re-analyse",
  "Notă de după": "Note after",
  "Peste țintă.": "Above target.",
  "Recapitulări": "Recaps",
  "Ideile zilei": "Today's ideas",
  "Filtru știri": "News filter",
  "Niciun titlu": "No headlines",
  "Trend follow": "Trend follow",
  "Profit factor": "Profit factor",
  "Întrebarea ta": "Your question",
  "Filtru alerte": "Alert filter",
  "Nimic necitit": "Nothing unread",
  "Cea mai slabă": "Worst",
  "Pe instrument": "By instrument",
  "O literă mare": "An uppercase letter",
  "Instituțional": "Institutional",
  "Salvează nota": "Save note",
  "Notă dinainte": "Note before",
  "Ce ai învățat": "What you learned",
  "Filtru jurnal": "Journal filter",
  "fără rezultat": "no result",
  "Intră în cont": "Sign in",
  "Țintele lunii": "This month's targets",
  "Parolă uitată": "Forgot password",
  "Regulile tale": "Your rules",
  "Copiază cheia": "Copy key",
  "Fel de raport": "Report type",
  "Raport fiscal": "Tax report",
  "Adaugă simbol": "Add symbol",
  "Anunță-mă sub": "Alert me below",
  "Ieși din cont?": "Sign out?",
  "Toate setările": "All settings",
  "în desfășurare": "in progress",
  "plată restantă": "payment overdue",
  "ÎNCEPE DE AICI": "START HERE",
  "Rată de câștig": "Win rate",
  "Pierdere medie": "Average loss",
  "Curba contului": "Equity curve",
  "Strategie nouă": "New strategy",
  "Săptămâna asta": "This week",
  "Ce mișcă piața": "What moves the market",
  "Creează echipa": "Create team",
  "Creează contul": "Create account",
  "Ce fel de cont": "What kind of account",
  "Ultima cotație": "Last quote",
  "Adaugă un cont": "Add an account",
  "Alege fișierul": "Choose file",
  "Rânduri sărite": "Rows skipped",
  "Am mutat SL-ul": "I moved the SL",
  "Confirmă codul": "Confirm code",
  "Trimite linkul": "Send link",
  "Export de date": "Data export",
  "Rezumat fiscal": "Tax summary",
  "Ce tipar cauți": "What pattern are you after",
  "Se va salva ca": "Will be saved as",
  "Mai adaugă una": "Add another",
  "Închide meniul": "Close menu",
  "Vezi rezultatul": "See result",
  "Pe ora intrării": "By entry hour",
  "Rularea a eșuat": "Run failed",
  "Alege strategia": "Choose strategy",
  "Scrie o postare": "Write a post",
  "Ținta de profit": "Profit target",
  "Avantajele tale": "Your edges",
  "Rezultat salvat": "Result saved",
  "Câștig la țintă": "Win at target",
  "Data exportului": "Export date",
  "Expectancy în R": "Expectancy in R",
  "După tranzacție": "After the trade",
  "Bine ai revenit": "Welcome back",
  "Alerte necitite": "Unread alerts",
  "Știri cu impact": "High-impact news",
  "Restricție luni": "Monday restriction",
  "Codul nu e bun.": "That code isn't right.",
  "Bază impozabilă": "Taxable base",
  "Impozit estimat": "Estimated tax",
  "Pentru contabil": "For your accountant",
  "Stop pentru azi": "Stop for today",
  "Anunță-mă peste": "Alert me above",
  "Jurnal detaliat": "Detailed journal",
  "De ce ai intrat?": "Why did you enter?",
  "Întreabă altceva": "Ask something else",
  "Caută un termen…": "Search a term…",
  "Doar impact mare": "High impact only",
  "Niciun eveniment": "No events",
  "Resetează bifele": "Reset ticks",
  "Fă o echipă nouă": "Create a new team",
  "Prea puține date": "Not enough data",
  "Ieșire (închide)": "Exit (close)",
  "Mărimea poziției": "Position size",
  "Niveluri marcate": "Marked levels",
  "Import și export": "Import and export",
  "Cum să-ți spunem": "What should we call you",
  "Intrare → ieșire": "Entry → exit",
  "gol = fără țintă": "empty = no target",
  "Rezultatul zilei": "Today's result",
  "Poziții deschise": "Open positions",
  "Revizuirea zilei": "Day review",
  "Oprește doi pași": "Turn off two-step",
  "Ce se scrie acum": "What's being written now",
  "Poziție deschisă": "Open position",
  "Adaugă o captură": "Add a screenshot",
  "Scoate pragurile": "Remove thresholds",
  "Deschide uneltele": "Open tools",
  "Nu l-ai dat încă.": "You haven't taken it yet.",
  "Lumânări parcurse": "Candles processed",
  "Simbol (opțional)": "Symbol (optional)",
  "Broker (opțional)": "Broker (optional)",
  "Toate defalcările": "All breakdowns",
  "Șterge tranzacția": "Delete trade",
  "Atinge unde intri": "Tap where you enter",
  "Acum atinge ținta": "Now tap the target",
  "Format recunoscut": "Format recognised",
  "Raporturi de risc": "Risk ratios",
  "Alege parola nouă": "Choose a new password",
  "Tranzacții vineri": "Friday trades",
  "Idem, pentru luni": "Same, for Monday",
  "Salvează profilul": "Save profile",
  "Exportă-mi datele": "Export my data",
  "Ultima confirmare": "Final confirmation",
  "Pornește doi pași": "Turn on two-step",
  "Aproape de limită": "Close to the limit",
  "Poți tranzacționa": "You can trade",
  "Salvează limitele": "Save limits",
  "Niciun semnal azi": "No signals today",
  "Puterea valutelor": "Currency strength",
  "Deschide graficele": "Open charts",
  "N-ai înțeles ceva?": "Something unclear?",
  "Scrie o întrebare…": "Type a question…",
  "Fă prima strategie": "Build your first strategy",
  "Parametrii rulării": "Run parameters",
  "Rulează backtestul": "Run backtest",
  "Raport risc/câștig": "Risk/reward ratio",
  "Despre ce e vorba?": "What's it about?",
  "Grupuri de trading": "Trading groups",
  "Maxim în fereastră": "High in window",
  "Minim în fereastră": "Low in window",
  "Lumânări încărcate": "Candles loaded",
  "Tranzacții în cont": "Trades in account",
  "Continuă cu Google": "Continue with Google",
  "prea puțin istoric": "too little history",
  "Niciuna, nici alta": "Neither one",
  "Unde ajunge contul": "Where the account ends up",
  "Prop firm și piață": "Prop firm and market",
  "Nu am putut salva.": "Couldn't save.",
  "Drawdown, consumat": "Drawdown used",
  "Tranzacții închise": "Closed trades",
  "Limitele tale, azi": "Your limits, today",
  "Ieșire din sesiune": "Session exit",
  "Break of Structure": "Break of Structure",
  "Nimic urmărit încă": "Nothing watched yet",
  "Sugerează prag sub": "Suggest threshold below",
  "Salvează pragurile": "Save thresholds",
  "Salvează tranzacția": "Save trade",
  "Termeni și condiții": "Terms and conditions",
  "Marchează terminată": "Mark as done",
  "Niciun termen găsit": "No term found",
  "Adaugă o tranzacție": "Add a trade",
  "sub 1 = în pierdere": "below 1 = losing",
  "Golește conversația": "Clear conversation",
  "Adu lista implicită": "Restore the default list",
  "Ce discută ceilalți": "What others are discussing",
  "Nu am putut șterge.": "Couldn't delete.",
  "Analizează graficul": "Analyse the chart",
  "Am ignorat regulile": "I ignored my rules",
  "Număr de tranzacții": "Number of trades",
  "Trimite comentariul": "Post comment",
  "Raportul săptămânii": "Weekly report",
  "Conectează Telegram": "Connect Telegram",
  "Codul de șase cifre": "The six-digit code",
  "Limitele conturilor": "Account limits",
  "Editează tranzacția": "Edit trade",
  "Change of Character": "Change of Character",
  "Se deschide Google…": "Opening Google…",
  "în perioada de probă": "in trial",
  "Cuvintele din lecții": "Words from the lessons",
  "Încă nu e ce analiza": "Nothing to analyse yet",
  "Nicio strategie încă": "No strategy yet",
  "Analiza nu a pornit.": "The analysis didn't start.",
  "Șterge ultimul desen": "Undo last drawing",
  "tranzacție importată": "trade imported",
  "tranzacții importate": "trades imported",
  "Fără date suficiente": "Not enough data",
  "nicio zi în pierdere": "no losing day",
  "Cotațiile nu răspund": "Quotes aren't responding",
  "Scrie un comentariu…": "Write a comment…",
  "Analiză AI, duminica": "AI analysis, on Sundays",
  "Confirmă și pornește": "Confirm and start",
  "Pune regulile firmei": "Set the firm's rules",
  "Încrucișare de medii": "Moving average crossover",
  "Sugerează prag peste": "Suggest threshold above",
  "Deschide calculatorul": "Open calculator",
  "Nu am primit răspuns.": "No response received.",
  "Vezi ultimul rezultat": "See last result",
  "Distanța până la stop": "Distance to stop",
  "Câștig la take profit": "Win at take profit",
  "Niciun eveniment mare": "No major events",
  "Pierdere zilnică max.": "Max daily loss",
  "Vezi: toate conturile": "Showing: all accounts",
  "gol = rămâne deschisă": "empty = stays open",
  "Ce merită ținut minte": "Worth remembering",
  "Importul nu a reușit.": "Import failed.",
  "Cel puțin 8 caractere": "At least 8 characters",
  "Vedere instituțională": "Institutional view",
  "Înainte de tranzacție": "Before the trade",
  "Deconectează Telegram": "Disconnect Telegram",
  "Raport de performanță": "Performance report",
  "Cum a mers, pe hârtie": "How it went, on paper",
  "Sold inițial → curent": "Starting → current balance",
  "Azi nu tranzacționezi": "No trading today",
  "Pe trend, la corecție": "With the trend, on a pullback",
  "Abonament și facturare": "Subscription and billing",
  "Rată de câștig pe zile": "Win rate by day",
  "Niciun cont de trading": "No trading account",
  "Cum a decurs execuția?": "How did the execution go?",
  "Prea puține tranzacții": "Too few trades",
  "Ce ai făcut azi, seara": "What you did today, in the evening",
  "Nu am putut deconecta.": "Couldn't disconnect.",
  "Nimic de raportat încă": "Nothing to report yet",
  "Ai atins numărul maxim": "You've hit the maximum",
  "Generarea nu a pornit.": "Generation didn't start.",
  "Întoarcere din extreme": "Reversal from extremes",
  "Nu m-am putut conecta.": "Couldn't connect.",
  "Lecția nu a fost găsită": "Lesson not found",
  "Ce anume n-a fost clar?": "What exactly wasn't clear?",
  "Modulul nu a fost găsit": "Module not found",
  "Modulul ăsta n-are quiz": "This module has no quiz",
  "Nouă module, de la zero": "Nine modules, from scratch",
  "Banii tăi, la un broker": "Your own money, at a broker",
  "Rezultat din tranzacții": "Result from trades",
  "scăderile nu se plătesc": "the drawdowns don't pay off",
  "Tranzacții de răzbunare": "Revenge trades",
  "Șterge contul definitiv": "Delete account permanently",
  "Regulile challenge-ului": "Challenge rules",
  "Schimbă regulile firmei": "Change the firm's rules",
  "Pierdere zilnică maximă": "Max daily loss",
  "Analiza AI nu e pornită": "AI analysis isn't enabled",
  "Cele două care contează": "The two that matter",
  "Nu am găsit tranzacția.": "Trade not found.",
  "Notează prima tranzacție": "Log your first trade",
  "Reguli și limite de risc": "Rules and risk limits",
  "Ce primești și cât costă": "What you get and what it costs",
  "Glosarul nu s-a încărcat": "The glossary didn't load",
  "Nu am putut crea echipa.": "Couldn't create the team.",
  "Nu am putut crea contul.": "Couldn't create the account.",
  "Nicio tranzacție închisă": "No closed trades",
  "Mii de vieți alternative": "Thousands of alternative lives",
  "Vreau să-mi șterg contul": "I want to delete my account",
  "Niciun cont de challenge": "No challenge account",
  "Administrează abonamentul": "Manage subscription",
  "Lecțiile nu s-au încărcat": "The lessons didn't load",
  "În fusul telefonului tău.": "In your phone's timezone.",
  "Expectancy per tranzacție": "Expectancy per trade",
  "Nu am putut aduce prețul.": "Couldn't fetch the price.",
  "Codul nu a fost acceptat.": "The code wasn't accepted.",
  "Sincronizează cu brokerul": "Sync with broker",
  "Ce s-a întâmplat de fapt.": "What actually happened.",
  "Postarea nu a fost găsită": "Post not found",
  "Anunțuri care mișcă piața": "Announcements that move the market",
  "Generează semnalele zilei": "Generate today's signals",
  "Simbolul e deja în listă.": "That symbol is already on the list.",
  "Adaugă o regulă personală…": "Add a rule of your own…",
  "Un al doilea cont cere PRO": "A second account requires PRO",
  "Sincronizarea nu a pornit.": "The sync didn't start.",
  "Nicio tranzacție importată": "No trades imported",
  "Expectancy în bani și în R": "Expectancy in money and in R",
  "Payoff (câștig / pierdere)": "Payoff (win / loss)",
  "Analiza AI e în planul PRO": "AI analysis is on the PRO plan",
  "Ce credeai când ai intrat.": "What you believed when you entered.",
  "Toate tranzacțiile au notă": "Every trade has a note",
  "Limita zilnică de pierdere": "Daily loss limit",
  "Nu am putut șterge contul.": "Couldn't delete the account.",
  "Scrie ȘTERG ca să confirmi": "Type DELETE to confirm",
  "Pierderea zilei, consumată": "Today's loss, used",
  "Obiceiurile tale, măsurate": "Your habits, measured",
  "Nicio știre de impact mare": "No high-impact news",
  "Nu am putut urca imaginea.": "Couldn't upload the image.",
  "Nu am putut citi imaginea.": "Couldn't read the image.",
  "Nu am putut genera PDF-ul.": "Couldn't generate the PDF.",
  "Nu am putut schimba contul.": "Couldn't switch account.",
  "Tranzacția nu a fost găsită": "Trade not found",
  "Acum atinge unde pui stopul": "Now tap where you place the stop",
  "Apasă pe linkul de resetare": "Tap the reset link",
  "Înainte s-o atingi, nu după": "Before you hit it, not after",
  "Nu am putut exporta datele.": "Couldn't export your data.",
  "Trimite-mi link de resetare": "Send me a reset link",
  "Nu am putut trimite linkul.": "Couldn't send the link.",
  "Adaugă un cont de challenge": "Add a challenge account",
  "Nu am putut salva regulile.": "Couldn't save the rules.",
  "Ce s-a livrat și ce urmează": "What shipped and what's next",
  "Nu am putut șterge captura.": "Couldn't delete the screenshot.",
  "Nu am putut scrie fișierul.": "Couldn't write the file.",
  "Nu am putut deschide plata.": "Couldn't open the payment page.",
  "Intră cu un cod de invitație": "Join with an invite code",
  "Cont de prop firm, cu reguli": "Prop firm account, with rules",
  "Unde ai avantaj, unde pierzi": "Where you have an edge, where you lose",
  "Nicio tranzacție notată încă": "No annotated trades yet",
  "Toate sesiunile sunt închise": "All sessions are closed",
  "Nu am putut salva strategia.": "Couldn't save the strategy.",
  "Nu am putut adăuga simbolul.": "Couldn't add the symbol.",
  "Nu am putut scoate simbolul.": "Couldn't remove the symbol.",
  "Nu am putut salva pragurile.": "Couldn't save the thresholds.",
  "Politica de confidențialitate": "Privacy policy",
  "Verific starea abonamentului…": "Checking your subscription…",
  "Ai terminat backtestele lunii": "You've used this month's backtests",
  "Nu am putut trimite postarea.": "Couldn't post that.",
  "Bani virtuali, pentru exersat": "Virtual money, for practice",
  "Nu mai ai nimic de completat.": "Nothing left to fill in.",
  "Drawdown mediu al simulărilor": "Average drawdown across simulations",
  "Nu am putut conecta Telegram.": "Couldn't connect Telegram.",
  "Ți-am trimis linkul pe email.": "We've emailed you the link.",
  "Se aplică pe toate conturile.": "Applies to every account.",
  "Ideile zilei, analizate de AI": "Today's ideas, analysed by AI",
  "Serverul n-a întors o adresă.": "The server didn't return an address.",
  "Vede statisticile contului tău": "Sees your account statistics",
  "Fără date pentru simbolul ăsta": "No data for this symbol",
  "Nu am putut salva obiectivele.": "Couldn't save your goals.",
  "Lasă gol ce nu te interesează.": "Leave blank what you don't care about.",
  "Deschide emailul de la TradeGX": "Open the email from TradeGX",
  "Pentru tine și pentru contabil": "For you and for your accountant",
  "Regulile tale sunt respectate.": "Your rules are being followed.",
  "Pe ce simbol pierd cel mai des?": "Which symbol do I lose on most?",
  "Strategiile tale, pe date reale": "Your strategies, on real data",
  "Ești pregătit să tranzacționezi": "You're ready to trade",
  "riscul de scădere e bine plătit": "the downside risk pays well",
  "Intrări imediat după o pierdere": "Entries right after a loss",
  "Nu am putut porni configurarea.": "Couldn't start the setup.",
  "PDF gata de trimis contabilului": "PDF ready to send to your accountant",
  "Apasă lung ca să ștergi captura": "Press and hold to delete the screenshot",
  "Corelațiile nu sunt disponibile": "Correlations aren't available",
  "Nu am putut termina conectarea.": "Couldn't finish signing in.",
  "Tutorele e inclus în planul PRO.": "The tutor is included in the PRO plan.",
  "Drawdown-ul mediu al simulărilor": "The average drawdown across simulations",
  "Răspuns neașteptat de la server.": "Unexpected response from the server.",
  "Ce ar trebui să opresc luna asta?": "What should I stop doing this month?",
  "Întoarce-te aici și intră în cont": "Come back here and sign in",
  "Primești alertele și pe Telegram.": "You also get alerts on Telegram.",
  "Simbolurile tale și pragurile lor": "Your symbols and their thresholds",
  "Asistentul e inclus în planul PRO.": "The assistant is included in the PRO plan.",
  "Ideea, greșeala sau întrebarea ta.": "Your idea, mistake or question.",
  "Toate tranzacțiile, ca fișier CSV.": "Every trade, as a CSV file.",
  "Cod din aplicația de autentificare": "Code from your authenticator app",
  "Intrări după o mișcare deja făcută": "Entries after the move has already happened",
  "Toate pragurile se scriu în cifre.": "All thresholds must be numbers.",
  "Defalcare pe luni și pe instrument": "Breakdown by month and by instrument",
  "Ordonate după cât de aproape ești.": "Sorted by how close you are.",
  "Comutare între ele dintr-o atingere": "Switch between them with one tap",
  "Analiza graficului e în planul PRO.": "Chart analysis is on the PRO plan.",
  "Trage cu un deget · apropie cu două": "Drag with one finger · pinch with two",
  "Cifrele pe care le cere un alocator": "The numbers an allocator asks for",
  "Dacă ți-ai pus vinerea ca zi liberă": "If you marked Friday as a day off",
  "Caută botul TradeGx și apasă Start.": "Find the TradeGx bot and tap Start.",
  "Nu am putut deschide administrarea.": "Couldn't open the management page.",
  "Scrie Chat ID-ul aici și conectează.": "Enter your Chat ID here and connect.",
  "Nu am putut salva limitele contului.": "Couldn't save the account limits.",
  "Vedere agregată pe toate, când o vrei": "An aggregate view across all of them, whenever you want",
  "Contul pe care îl urmărește aplicația": "The account the app is tracking",
  "Mută tranzacțiile în și din aplicație": "Move trades in and out of the app",
  "Nu am putut salva. Verifică semnalul.": "Couldn't save. Check your signal.",
  "De ce ai intrat? Ce vedeai în grafic?": "Why did you enter? What did you see on the chart?",
  "Mii de vieți alternative ale contului": "Thousands of alternative lives for your account",
  "Trei pași, mai jos. Durează un minut.": "Three steps, below. Takes a minute.",
  "Trei întrebări de dinainte de intrare": "Three questions to ask before entering",
  "Prima deschidere are nevoie de semnal.": "The first open needs a connection.",
  "La ce oră tranzacționez cel mai prost?": "What time of day do I trade worst?",
  "Disciplina, înainte de fiecare intrare": "Discipline, before every entry",
  "Când treci de riscul tău pe tranzacție": "When you exceed your per-trade risk",
  "Nicio tranzacție închisă în anul ăsta.": "No closed trades this year.",
  "Nu am putut deschide fereastra Google.": "Couldn't open the Google window.",
  "Serverul n-a întors o adresă de plată.": "The server didn't return a payment address.",
  "Nu am putut salva. Verifică internetul.": "Couldn't save. Check your connection.",
  "Rularea nu a pornit. Verifică semnalul.": "The run didn't start. Check your signal.",
  "Nu există cotație pentru simbolul ăsta.": "There's no quote for this symbol.",
  "căderea e mai mare decât câștigul anual": "the drawdown is bigger than the annual gain",
  "Raport risc/câștig calculat, nu estimat": "Risk/reward calculated, not estimated",
  "Nu am primit răspuns. Verifică semnalul.": "No response. Check your signal.",
  "O întrebare despre managementul riscului": "A question about risk management",
  "E o zi pe care tu ai marcat-o ca liberă.": "This is a day you marked as off.",
  "Scrie un simbol valid, de exemplu EURUSD.": "Enter a valid symbol, for example EURUSD.",
  "Lista se golește singură mâine dimineață.": "The list clears itself tomorrow morning.",
  "Setup-ul care îmi merge cel mai bine acum": "The setup working best for me right now",
  "Cât randament pe unitatea de risc asumat.": "How much return per unit of risk taken.",
  "Comentariul n-a ajuns. Verifică semnalul.": "The comment didn't go through. Check your signal.",
  "Se salvează singure, la fiecare comutare.": "Saved automatically, on every toggle.",
  "E cel mai lung șir al tău. Nu-l rupe azi.": "This is your longest streak. Don't break it today.",
  "Întoarce-te la modul și alege-o din listă.": "Go back to the module and pick it from the list.",
  "Promovat. Materia din modulul ăsta e a ta.": "Passed. The material in this module is yours.",
  "Bifele se resetează automat în fiecare zi.": "The ticks reset automatically every day.",
  "Conturi nelimitate, separate în statistici": "Unlimited accounts, kept separate in your stats",
  "Citește structura de pe intervalul afișat.": "Reads the structure on the displayed timeframe.",
  "Echitate finală, 100 = punctul de plecare.": "Final equity, 100 = the starting point.",
  "Nivelul de încredere și sesiunea potrivită": "The confidence level and the right session",
  "Nimic care să miște piața în ultimele ore.": "Nothing that would move the market in the last few hours.",
  "În ordinea în care se învață, nu alfabetic.": "In the order you learn them, not alphabetically.",
  "Care e cea mai costisitoare greșeală a mea?": "What is my most expensive mistake?",
  "Ce am învățat din ultimele 20 de tranzacții": "What I learned from my last 20 trades",
  "Poate a fost ștearsă. Întoarce-te la listă.": "It may have been deleted. Go back to the list.",
  "Nu m-am putut conecta. Verifică internetul.": "Couldn't connect. Check your internet.",
  "randament mare față de cea mai urâtă cădere": "high return against the ugliest drawdown",
  "Sharpe, Sortino și Calmar pe curba ta reală": "Sharpe, Sortino and Calmar on your real curve",
  "Calculat pe toate conturile, cum se declară": "Calculated across all accounts, the way it's declared",
  "Încearcă alt cuvânt, sau caută în definiții.": "Try another word, or search the definitions.",
  "Scurgerile — tiparele care te costă constant": "The leaks — the patterns that cost you consistently",
  "Setup complet. O atingere nouă începe altul.": "Setup complete. A new tap starts another one.",
  "Defalcare pe conturi, comparabilă cap la cap": "Breakdown by account, comparable side by side",
  "Atins. Nu forța peste — numărul nu e scopul.": "Reached. Don't push past it — the number isn't the point.",
  "Contul și tot ce conține dispar acum. Sigur?": "The account and everything in it disappear now. Sure?",
  "Alege un tipar, apoi rulează-l pe date reale": "Pick a pattern, then run it on real data",
  "Barele sunt pe accent: nu e P&L, e frecvență.": "The bars use the accent colour: this isn't P&L, it's frequency.",
  "Media variațiilor zilei, pe perechile majore.": "The average of the day's moves, across the major pairs.",
  "Fără conexiune. Trage în jos ca să reîncerci.": "No connection. Pull down to retry.",
  "Presetul umple regulile; le poți schimba după.": "The preset fills in the rules; you can change them after.",
  "Comparabile cap la cap, fiecare cu riscul lui.": "Comparable side by side, each with its own risk.",
  "Notele se scriu după ce tranzacția s-a închis.": "Notes are written after the trade has closed.",
  "Scrie codul din aplicația ta de autentificare.": "Enter the code from your authenticator app.",
  "Nu s-a șters nimic — cuvântul nu s-a potrivit.": "Nothing was deleted — the word didn't match.",
  "Istoric pe fiecare an în care ai tranzacționat": "History for every year you traded",
  "RSI 14 sub 30 sau peste 70, filtrat de EMA 50.": "RSI 14 below 30 or above 70, filtered by EMA 50.",
  "Regulile strategiei rămân cele salvate pe site.": "The strategy rules stay as saved on the website.",
  "Greșeala care m-a costat cel mai mult luna asta": "The mistake that cost me most this month",
  "Reguli de prop firm urmărite separat pe fiecare": "Prop firm rules tracked separately for each one",
  "Atinge graficul ca să pui o linie la prețul ăla": "Tap the chart to place a line at that price",
  "Când tranzacționezi mai mult decât ți-ai propus": "When you trade more than you set out to",
  "Alertele ajung și acolo, nu doar ca notificare.": "Alerts arrive there too, not just as a notification.",
  "Intrare, stop și două ținte pentru fiecare idee": "Entry, stop and two targets for every idea",
  "Nu am putut încărca lecțiile. Verifică semnalul.": "Couldn't load the lessons. Check your signal.",
  "CSV de la broker, sau raportul HTML din MT4/MT5.": "A CSV from your broker, or the HTML report from MT4/MT5.",
  "Probabilitatea de a atinge ținta și cea de ruină": "The probability of hitting the target and the probability of ruin",
  "Banda largă = 90% din simulări. Linia = mediana.": "The wide band = 90% of simulations. The line = the median.",
  "Nu am putut salva preferința. Verifică semnalul.": "Couldn't save the preference. Check your signal.",
  "Chat ID-ul e un număr, de obicei din nouă cifre.": "The Chat ID is a number, usually nine digits.",
  "Oprită. Cu ea, parola singură nu mai e de ajuns.": "Off. With it on, your password alone isn't enough.",
  "Se poate trăi cu ea, dar nu are marjă de eroare.": "You can live with it, but it leaves no margin for error.",
  "Conectarea cu Google n-a mers. Încearcă din nou.": "Google sign-in didn't work. Try again.",
  "Jurnal cu note înainte și după fiecare tranzacție": "A journal with notes before and after every trade",
  "Randament anual împărțit la cea mai urâtă cădere.": "Annual return divided by the ugliest drawdown.",
  "Intră în contul tău și vezi cum ai tranzacționat.": "Sign in and see how you traded.",
  "EMA 9 taie EMA 21, cu EMA 200 ca filtru de trend.": "EMA 9 crosses EMA 21, with EMA 200 as the trend filter.",
  "Ce a fost setup-ul. Din astea iese Edge Finder-ul.": "What the setup was. This is what Edge Finder is built from.",
  "Google n-a confirmat conectarea. Încearcă din nou.": "Google didn't confirm the sign-in. Try again.",
  "Manager de risc care îți spune dacă mai ai voie azi": "A risk manager that tells you whether you're still allowed to trade today",
  "Ordonate după robustețe, nu după suma cea mai mare.": "Sorted by robustness, not by the biggest number.",
  "Conul de echitate: cât de larg e intervalul realist": "The equity cone: how wide the realistic range is",
  "Drawdown-ul se scrie în procente, între 0,1 și 100.": "Drawdown is written as a percentage, between 0.1 and 100.",
  "Sănătos. Regulile astea rezistă la o serie proastă.": "Healthy. These rules hold up through a bad run.",
  "Scrii o postare, ceilalți comentează și reacționează": "You write a post, others comment and react",
  "Rămân aici și mâine, pe simbolul și intervalul ăsta.": "They stay here tomorrow too, on this symbol and timeframe.",
  "O propoziție pe care vrei s-o citești data viitoare.": "One sentence you'll want to read next time.",
  "Toate tranzacțiile au notă. Asta e jurnalul complet.": "Every trade has a note. That's the full journal.",
  "Intervalul sesiunii Londra, spart în orice direcție.": "The London session range, broken in either direction.",
  "Limita zilnică de pierdere e atinsă. Mâine e altă zi.": "Your daily loss limit is hit. Tomorrow is another day.",
  "Va trebui să te autentifici din nou pe telefonul ăsta.": "You'll have to sign in again on this phone.",
  "Defalcare pe simbol, setup, sesiune, zi, oră și durată": "Breakdown by symbol, setup, session, day, hour and duration",
  "Caută tiparul pe un grafic real, pe intervale diferite.": "Look for the pattern on a real chart, across timeframes.",
  "Tutorele citește lecția asta și îți răspunde despre ea.": "The tutor reads this lesson and answers questions about it.",
  "Nu toate modulele au verificare. Întoarce-te la lecții.": "Not every module has a quiz. Go back to the lessons.",
  "Avantajele tale, ordonate după robustețe, nu după noroc": "Your edges, sorted by robustness, not by luck",
  "Analize: rată de câștig, profit factor, drawdown, Sharpe": "Analytics: win rate, profit factor, drawdown, Sharpe",
  "Academie completă: nouă module, lecții, quiz-uri, glosar": "A full academy: nine modules, lessons, quizzes, glossary",
  "CAGR și drawdown maxim, pe portofoliu și pe fiecare cont": "CAGR and max drawdown, for the portfolio and each account",
  "Fișierul de mai jos conține datele brute, în format JSON.": "The file below contains the raw data, in JSON format.",
  "Pierderea zilnică se scrie în procente, între 0,1 și 100.": "Daily loss is written as a percentage, between 0.1 and 100.",
  "Contul a fost creat. Verifică internetul și intră în cont.": "The account was created. Check your connection and sign in.",
  "Abonamentul se gestionează pe site, din meniul „Mai mult”.": "Your subscription is managed on the website, from the “More” menu.",
  "Cât rezistă contul cu regulile tale, pe 200 de tranzacții.": "How long the account survives under your rules, over 200 trades.",
  "Edge Finder — unde chiar ai avantaj și unde pierzi constant": "Edge Finder — where you really have an edge and where you consistently lose",
  "Săptămâna asta n-are anunțuri de impact mare. Zi liniștită.": "There are no high-impact announcements this week. A quiet stretch.",
  "Sursa de calendar nu a întors nimic pentru intervalul ăsta.": "The calendar source returned nothing for this range.",
  "Tiparele care te costă. Astea se opresc, nu se optimizează.": "The patterns that cost you. These get stopped, not optimised.",
  "Pe randamentele tale reale, fără ipoteze despre distribuție": "On your real returns, with no assumptions about the distribution",
  "Condiția de confirmare și cea de invalidare, scrise explicit": "The confirmation and the invalidation condition, written out explicitly",
  "Plățile nu sunt pornite momentan pe server. Revino în curând.": "Payments aren't enabled on the server right now. Come back soon.",
  "Pune stopul unde crezi și vezi ce lot iese pentru riscul tău.": "Put the stop where you think it goes and see what lot size your risk allows.",
  "Codul nu e bun. Verifică ora telefonului și încearcă din nou.": "That code isn't right. Check your phone's clock and try again.",
  "Forma, nu suma. Un salt brusc e la fel de suspect ca o cădere.": "The shape, not the total. A sudden jump is as suspicious as a drop.",
  "Titlul are nevoie de minim 3 caractere, iar textul de minim 10.": "The title needs at least 3 characters, and the body at least 10.",
  "Pragurile se verifică din zece în zece minute, nu în timp real.": "Thresholds are checked every ten minutes, not in real time.",
  "Completează simbol, intrare și stop loss ca să calculez volumul.": "Fill in symbol, entry and stop loss so I can work out the size.",
  "Poate a fost redenumit. Întoarce-te la listă și alege-l de acolo.": "It may have been renamed. Go back to the list and pick it there.",
  "Eșantion minim de 5 tranzacții, ca să nu tragi concluzii din trei": "A minimum sample of 5 trades, so you don't draw conclusions from three",
  "Fluxurile de știri nu răspund acum. Trage în jos ca să reîncerci.": "The news feeds aren't responding. Pull down to retry.",
  "Cumpără când RSI e jos și vinde când e sus, cu o medie ca filtru.": "Buy when RSI is low and sell when it's high, with a moving average as filter.",
  "Îți trimitem un link pe email. Îl deschizi și alegi o parolă nouă.": "We'll email you a link. Open it and choose a new password.",
  "EMA 50 ca direcție, ADX peste 25 ca putere, trei bare de corecție.": "EMA 50 for direction, ADX above 25 for strength, three pullback bars.",
  "Echipele sunt grupuri închise — intri cu un cod primit de la cineva": "Teams are closed groups — you join with a code someone gives you",
  "Randament peste volatilitatea totală. Peste 1 e bun, peste 2 e rar.": "Return over total volatility. Above 1 is good, above 2 is rare.",
  "Marchează intervalul unei sesiuni și intră când prețul iese din el.": "Mark a session's range and enter when price breaks out of it.",
  "Prea mare. Scade riscul pe tranzacție sau crește raportul de câștig.": "Too high. Lower your per-trade risk or raise your reward ratio.",
  "Deschide Telegram și caută @userinfobot — îți trimite Chat ID-ul tău.": "Open Telegram and search for @userinfobot — it sends you your Chat ID.",
  "Intră când media rapidă taie media lentă, în direcția trendului mare.": "Enter when the fast average crosses the slow one, in the direction of the higher trend.",
  "Așteaptă o corecție într-un trend confirmat și intră în direcția lui.": "Wait for a pullback in a confirmed trend and enter in its direction.",
  "Apasă pe un cont ca să-i pui pragurile. Se aplică doar contului ăluia.": "Tap an account to set its thresholds. They apply to that account only.",
  "Ca Sharpe, dar pedepsește doar scăderile. Urcările bruște nu sunt risc.": "Like Sharpe, but it only penalises the drops. Sharp rises aren't risk.",
  "După ora UTC. Suprapunerea Londra–New York e cea mai lichidă fereastră.": "By UTC hour. The London–New York overlap is the most liquid window.",
  "Furnizorul de prețuri nu e disponibil acum. Trage în jos ca să reîncerci.": "The price provider isn't available right now. Pull down to retry.",
  "În Unelte, combină rata de câștig cu raportul risc/câștig și vezi ce iese.": "In Tools, combine your win rate with your risk/reward ratio and see what comes out.",
  "Contul a fost creat. Intră cu emailul și parola pe care tocmai le-ai ales.": "The account was created. Sign in with the email and password you just chose.",
  "Aici vor apărea ultimele tranzacții, după ce adaugi un cont și notezi prima.": "Your latest trades will show up here, once you add an account and log the first one.",
  "Dacă adresa există la noi, ai primit un link de resetare. Expiră într-o oră.": "If that address is registered with us, a reset link is on its way. It expires in an hour.",
  "Restul parametrilor rămân la valorile cunoscute. Se schimbă pe site, dacă vrei.": "The remaining parameters keep their saved values. Change them on the website if you want.",
  "Adaugă un simbol mai sus, apoi pune-i un prag. Te anunțăm când prețul îl trece.": "Add a symbol above, then set a threshold. We'll tell you when price crosses it.",
  "Pe ecranul de Grafice ai lumânări reale, cu tranzacțiile tale marcate peste ele.": "The Charts screen gives you real candles, with your trades marked on them.",
  "Fără variațiile zilei nu se poate calcula puterea. Trage în jos ca să reîncerci.": "Without the day's moves, strength can't be calculated. Pull down to retry.",
  "Calculul are nevoie de istoric zilnic pentru toate perechile. Revino mai târziu.": "The calculation needs daily history for every pair. Come back later.",
  "În Unelte, la Risc de ruină, mută riscul pe tranzacție și vezi cât rezistă contul.": "In Tools, under Risk of ruin, move the per-trade risk and see how long the account survives.",
  "Planul gratuit include trei backteste pe lună. Abonamentul se gestionează pe site.": "The free plan includes three backtests a month. Your subscription is managed on the website.",
  "Poți lega postarea de un simbol, ca s-o găsească cine tranzacționează același lucru": "You can attach a symbol to the post, so people trading the same thing can find it",
  "Contul e creat, dar regulile firmei n-au ajuns. Le poți pune din ecranul Prop firm.": "The account was created, but the firm's rules didn't go through. You can set them from the Prop firm screen.",
  "Tranzacțiile importate intră într-un cont, ca să se știe pe ce sold s-au întâmplat.": "Imported trades go into an account, so it's clear which balance they happened on.",
  "Încearcă în calculatorul de lot: schimbă riscul și vezi cum se mută mărimea poziției.": "Try it in the lot calculator: change the risk and watch the position size move.",
  "Export generat de TradeGx la cererea ta, conform dreptului la portabilitatea datelor.": "Export generated by TradeGx at your request, under your right to data portability.",
  "Fie analiza n-a rulat încă, fie n-a găsit nimic care să merite. Poți cere o rulare acum.": "Either the analysis hasn't run yet, or it found nothing worth flagging. You can request a run now.",
  "Nu pot calcula valoarea pipului pentru simbolul ăsta pe contul tău. Scrie volumul manual.": "I can't work out the pip value for this symbol on your account. Enter the size manually.",
  "Sub prag. Recitește lecțiile la care ai ezitat și reia — scorul salvat rămâne cel mai bun.": "Below the threshold. Re-read the lessons you hesitated on and retake it — the score we keep is your best one.",
  "Alertele apar când o limită e atinsă, un preț ajunge la nivel sau un cont se sincronizează.": "Alerts appear when a limit is hit, a price reaches a level, or an account syncs.",
  "Nicio tranzacție închisă încă. Aici ajung după ce le închizi, cu rezultatul final și nota ta.": "No closed trades yet. They land here once you close them, with the final result and your note.",
  "Fără detalii. Cel mai des, furnizorul n-are lumânări pentru simbolul ăsta pe intervalul cerut.": "No details. Most often, the provider has no candles for this symbol on the requested timeframe.",
  "Serviciul de analiză nu e configurat momentan. Nu e ceva ce poți repara tu — revino mai târziu.": "The analysis service isn't configured right now. This isn't something you can fix — come back later.",
  "Aplicația măsoară ce se întâmplă într-un cont: sold, rezultate, limite. Fără unul, n-are ce urmări.": "The app measures what happens inside an account: balance, results, limits. Without one, there's nothing to track.",
  "Dispare din jurnal împreună cu nota scrisă la ea, și iese din toate statisticile. Nu se poate anula.": "It disappears from the journal along with the note attached to it, and drops out of every statistic. This can't be undone.",
  "Nicio poziție deschisă acum. Aici apar tranzacțiile cât timp sunt în piață, cu profitul care se mișcă.": "No open positions right now. Trades show up here while they're in the market, with the profit moving.",
  "Randamentul singur nu spune nimic despre cât a costat. Ecranul ăsta arată cât ai riscat ca să-l obții.": "Return on its own says nothing about what it cost. This screen shows how much you risked to get it.",
  "Îți taie istoricul pe opt dimensiuni și îți spune care combinații chiar produc bani — și care îi scurg.": "It slices your history eight ways and tells you which combinations actually make money — and which leak it.",
  "Furnizorul de cotații n-are istoric pentru combinația asta de simbol și interval. Încearcă alt interval.": "The quote provider has no history for this symbol and timeframe combination. Try another timeframe.",
  "Planul gratuit include un singur cont de trading. Cu PRO poți urmări câte vrei, fiecare cu statisticile lui.": "The free plan includes a single trading account. With PRO you can track as many as you like, each with its own statistics.",
  "Câștigul brut, pierderea brută, baza impozabilă și impozitul estimat pentru anul ales — pe toate conturile, ca la Fisc.": "Gross gain, gross loss, taxable base and estimated tax for the selected year — across every account, the way the tax office sees it.",
  "În fiecare dimineață, o analiză a instrumentelor principale: unde e structura, unde e lichiditatea, ce ar invalida ideea.": "Every morning, an analysis of the main instruments: where the structure is, where the liquidity is, what would invalidate the idea.",
  "Impozitul e o ESTIMARE, calculată pe regulile generale. Nu înlocuiește un contabil și nu ține cont de situația ta particulară.": "The tax figure is an ESTIMATE, calculated on the general rules. It doesn't replace an accountant and doesn't account for your particular situation.",
  "Sharpe, Sortino și Calmar se calculează pe o curbă de echitate — adică pe mai multe zile cu tranzacții închise, nu pe una singură.": "Sharpe, Sortino and Calmar are calculated on an equity curve — that is, across several days with closed trades, not a single one.",
  "Raport generat de TradeGx din tranzacțiile înregistrate în cont. Cifrele sunt informative și nu constituie consultanță de investiții.": "Report generated by TradeGx from the trades recorded in your account. The figures are informational and do not constitute investment advice.",
  "Raportul adună ce s-a întâmplat: rezultat, rată de câștig, defalcare pe luni, instrumente și setup-uri. Are nevoie de tranzacții închise.": "The report gathers what happened: result, win rate, breakdown by month, instrument and setup. It needs closed trades.",
  "Rulează mii de variante ale acelorași tranzacții, în altă ordine, și îți arată în câte dintre ele contul ajunge la țintă — și în câte arde.": "It runs thousands of variations of the same trades, in a different order, and shows you in how many of them the account reaches the target — and in how many it burns.",
  "Rată de câștig, profit factor, drawdown, curba contului — toate se calculează din tranzacții închise. Notează prima și ecranul prinde viață.": "Win rate, profit factor, drawdown, equity curve — all of it is calculated from closed trades. Log the first one and the screen comes alive.",
  "Simularea reeșantionează randamentele TALE, deci are nevoie de cel puțin zece tranzacții închise. Sub atât, rezultatul ar descrie norocul, nu metoda.": "The simulation resamples YOUR returns, so it needs at least ten closed trades. Below that, the result would describe luck, not method.",
  "Nicio tranzacție încă. Notează-ți intrările pe măsură ce le faci — din ele se calculează tot restul: rata de câștig, tiparele care merg și cele care te costă.": "No trades yet. Log your entries as you make them — everything else is calculated from them: win rate, the patterns that work and the ones that cost you.",
  "Raport generat de TradeGx pe toate conturile, fiindcă impozitul se calculează pe persoană, nu pe cont. Verifică cifrele cu contabilul tău înainte de a le declara.": "Report generated by TradeGx across all accounts, because tax is calculated per person, not per account. Check the figures with your accountant before declaring them.",
  "Ecranul urmărește cele două limite care te pot elimina — pierderea zilei și drawdown-ul — plus ținta de profit. Are nevoie de un cont cu regulile firmei puse pe el.": "This screen tracks the two limits that can eliminate you — the daily loss and the drawdown — plus the profit target. It needs an account with the firm's rules set on it.",
  "Alege un tipar gata făcut — încrucișare de medii, ieșire din sesiune, întoarcere din extreme sau urmărire de trend — și rulează-l pe date reale în treizeci de secunde.": "Pick a ready-made pattern — moving average crossover, session breakout, reversal from extremes or trend following — and run it on real data in thirty seconds.",
  "Academia are nouă module, de la ce e un pip până la managementul riscului, cu laboratoare pe datele tale reale. Prima deschidere are nevoie de internet; după aceea cursul rămâne pe telefon.": "The academy has nine modules, from what a pip is to risk management, with labs on your real data. The first open needs internet; after that the course stays on your phone.",
  "Jurnalul tău de tranzacții. Notezi fiecare intrare — simbol, direcție, stop, rezultat — și din ele se calculează statisticile, tiparele și raportul lunar. Fără intrări notate, restul aplicației n-are ce analiza.": "Your trading journal. You log every entry — symbol, direction, stop, result — and the statistics, the patterns and the monthly report are all calculated from them. With nothing logged, the rest of the app has nothing to analyse.",
  "„Mai am voie azi?” se măsoară pe soldul unui cont — cât ai pierdut din el și cât îți permiți. Fără cont, nu există limită de calculat.": "“Am I still allowed to trade today?” is measured against an account balance — how much of it you've lost and how much you can afford. Without an account, there's no limit to calculate.",
  "Ca să spun „pierzi constant pe EURUSD dimineața”, am nevoie de cel puțin cinci tranzacții pe fiecare tipar. Sub atât aș descrie norocul, nu metoda.": "To say “you consistently lose on EURUSD in the morning”, I need at least five trades per pattern. Below that I'd be describing luck, not method.",
};
